spring.application.name=rdam-backend
spring.profiles.active=dev

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/rdam?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.sql.init.mode=never

rdam.jwt.secret=${JWT_SECRET:cambia-este-secret-en-produccion-minimo-32-caracteres}
rdam.jwt.expiration-citizen-ms=${JWT_EXP_CITIZEN:86400000}
rdam.jwt.expiration-operator-ms=${JWT_EXP_OPERATOR:14400000}

rdam.storage.path=${STORAGE_PATH:./storage/certificados}

server.port=${PORT:8080}

logging.level.ar.gob.pj.rdam=DEBUG
logging.level.org.springframework.security=INFO

# PlusPagos
rdam.pluspagos.url=${PLUSPAGOS_URL:http://localhost:3000}
rdam.pluspagos.merchant-guid=${PLUSPAGOS_MERCHANT_GUID:test-merchant-001}
rdam.pluspagos.secret-key=${PLUSPAGOS_SECRET_KEY:clave-secreta-campus-2026}
rdam.pluspagos.callback-url=${PLUSPAGOS_CALLBACK_URL:http://localhost:8080/api/v1/pagos/webhook}
rdam.pluspagos.url-success=${PLUSPAGOS_URL_SUCCESS:http://localhost:5173/pago/exitoso}
rdam.pluspagos.url-error=${PLUSPAGOS_URL_ERROR:http://localhost:5173/pago/error}
rdam.pluspagos.monto-centavos=${PLUSPAGOS_MONTO:150000}
